### ISSUE TITLE
What's the difference between "Clear movement data" and "Perform reset" ? [

### ISSUE THREAD

**Issue by triNem** [jansolo/aXbo-research#9]
<h3>What's the objective of "Clear movement data" ?

"Clear movement data" seems pretty straightforward : remove the movement logs. But then, when should I use this ? Does it influence the knowledge of the  waking hour that axbo develops ?

<h3>What's the objective of "Perform reset" ?

What about the "Perform reset" ? Is this only to remove the the alarm clock and the date or does it influence the knowledge of the  waking hour that axbo develops?

<h3>What's the difference between the two ?<h3>

<h3>And the difference between those and removing the batteries ?

I have also noticed after removing the batteries that the device looses the knowledge of the right waking hour. This is a problem since travels can be hectic and battery tend to dislodge themselves. 

<h3>Is it possible to save & restore this memory ?

**Comment by jansolo** [comment]
* "Clear movement data" only removes the movement log. It does not reset clock time and alarms. It does not influence the calculation of the waking hour. There is no need to clear the log data, because aXbo will override old data if the memory gets full (it works like a buffer). So clearing log data is only required, if you want this explicitly (for example if you sell your aXbo).
* "Perform reset" does not delete the movement log, but otherwise resets the aXbo alarm clock to factory settings. To my knowledge it does not influence the calculation of the waking hour, but it resets any alarms stored on the aXbo.
* It is not possible to save the configured alarms externally. Equally it is not possible to set the alarms from outside, but you can set date and time (which is done automatically when you reset aXbo from "aXbo research" software).
* If you remove the batteries you need to set date and time manually, either directly on the clock or via the "aXbo research" software.

**Comment by triNem** [comment]
Thank you very much. Your answer clarifies the different functionalities.

If I understand well, "Clear movement" data is for the logs. "Perform reset" is for the alarms and time. And apart from the logs it is impossible to save anything else.

I have a following question, though. 

<h4>What is Axbo using to "learn" the sleep pattern? 

I read at [axbo.zendesk.com] (https://axbo.zendesk.com/hc/en-us/articles/200605313-aXbo-wake-me-up-at-the-last-time-with-a-Pip-tone) that Axbo "learns" the sleep pattern over a few days. 

What are the criteria used to learn this sleep pattern ? If neither the logs nor the clock settings are  influencing the waking hour then what is there to learn ?

This seems important since this might influence the way I sleep (e.g. keeping a regular sleep rhythm for instance). Also, I have an old Axbo that no longer uses it's batteries. It seems to be less efficient at waking me up ever since this happened...

**Comment by jansolo** [comment]
Please contact aXbo.com to get information about the internal workings of Axbo, because I do not have access to the firmware.
